instance_name         = "prod-vm"
instance_machine_type = "e2-standard-4"
instance_zone         = "us-central1-c"
boot_disk_image       = "debian-cloud/debian-12"
boot_disk_size_gb     = 100
enable_external_ip    = false
instance_network_tags = ["ssh", "web"]
instance_metadata     = {}
vm_service_account_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
