instance_name         = "test-vm"
instance_machine_type = "e2-medium"
instance_zone         = "us-central1-b"
boot_disk_image       = "debian-cloud/debian-12"
boot_disk_size_gb     = 40
enable_external_ip    = true
instance_network_tags = ["ssh", "web"]
instance_metadata     = {}
vm_service_account_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
